version: "3.7"
services:
  app:
      build:
        args:
          user: aji
          uid: 1000
        context: ./
        dockerfile: ./Dockerfile
      image: spppaud
      container_name: spppaud-app
      working_dir: /var/www/
      volumes:
        - ./:/var/www
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
      mem_limit: 512m
      mem_reservation: 128M
      cpus: 0.5
      networks:
        - spppaud
  nginx:
    image: nginx:1.17-alpine
    container_name: spppaud-nginx
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    networks:
      - spppaud
  db:
    image: mariadb:latest
    container_name: spppaud-db
    ports:
      - 3306:3306
    volumes:
      - spppauddb:/var/lib/mysql
      - ./database:/database
    environment:
      MYSQL_ROOT_PASSWORD: password
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    networks:
      spppaud:
        ipv4_address: 10.5.0.99
  phpmyadmin:
    image: phpmyadmin
    container_name: spppaud-phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306 
      - UPLOAD_LIMIT=300M
    networks:
      - spppaud

volumes:
  spppauddb: 
    driver: local

networks:
  spppaud:
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: 10.5.0.0/24
            gateway: 10.5.0.1
